### ISSUE TITLE
Crates `solana-bpf-helloworld` and `solana-program` use different versions of `borsh` lib

### ISSUE THREAD

**Issue by Tirka** [solana-labs/example-helloworld#266]
Problem: function `solana_program::borsh::get_packed_len` doesn't work with types, which implement `borsh::shema::BorshSchema`.

The reason is that сrates `solana-bpf-helloworld` and `solana-program` use different versions of `borsh` lib.

Possible solutions:
- Update deps at `cargo.toml` and make sure both crates use same version of `borsh`:
```toml
[dependencies]
borsh = "=0.8.2"
borsh-derive = "=0.8.2"
solana-program = "=1.7.1"
```
- Re-export `borsh` types from `solana-program` crate
